# Generated by Django 5.0.6 on 2024-06-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetID', models.CharField(max_length=200)),
                ('assetDescription', models.CharField(max_length=200)),
                ('assetStreet', models.CharField(max_length=200)),
                ('assetPLZ', models.CharField(max_length=200)),
                ('assetTown', models.CharField(max_length=200)),
                ('assetStatus', models.CharField(max_length=200)),
                ('assetBuild', models.CharField(max_length=200)),
                ('assetType', models.CharField(max_length=200)),
                ('assetSubtenant', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyID', models.CharField(max_length=200)),
                ('companyName', models.CharField(max_length=200)),
                ('companyStreet', models.CharField(max_length=200)),
                ('companyPLZ', models.CharField(max_length=200)),
                ('companyTown', models.CharField(max_length=200)),
                ('companyBranche', models.CharField(max_length=200)),
                ('companyEmail', models.EmailField(max_length=200)),
                ('companyPhone', models.CharField(max_length=200)),
                ('companyTradingID', models.CharField(max_length=200)),
                ('companyCourt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractName', models.CharField(max_length=200)),
                ('contractTyp', models.CharField(max_length=200)),
                ('contractLeasingCompany', models.CharField(max_length=500)),
                ('companyID', models.CharField(max_length=500)),
                ('contractStart', models.CharField(max_length=200)),
                ('contractRuntime', models.CharField(max_length=200)),
                ('contractEnd', models.CharField(max_length=500)),
                ('contractRhythm', models.CharField(max_length=200)),
                ('contractPaymentType', models.CharField(max_length=200)),
                ('contractInvestment', models.CharField(max_length=500)),
                ('contractDirectDebit', models.CharField(max_length=200)),
                ('assetID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(max_length=200)),
                ('contractID', models.CharField(max_length=200)),
                ('eventName', models.CharField(max_length=200)),
                ('eventDate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Formular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceID', models.CharField(max_length=200)),
                ('invoiceDate', models.CharField(max_length=200)),
                ('invoiceCosts', models.CharField(max_length=200)),
                ('invoiceStatus', models.CharField(max_length=200)),
                ('contractID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=200)),
                ('userLastName', models.CharField(max_length=200)),
                ('userFirstName', models.CharField(max_length=200)),
                ('userEmail', models.CharField(max_length=200)),
                ('userPhone', models.CharField(max_length=200)),
                ('companyID', models.CharField(max_length=200)),
            ],
        ),
    ]
